### ISSUE TITLE
Having trouble replicating metrics using Liu Feng's checkpoint

### ISSUE THREAD

**Issue by brresnic** [alanngnet/CoverHunterMPS#41]
#### Issue
In his original readme, Liu Feng indicates that the provided checkpoint should generate the following metrics on covers80:
```
2023-07-05 16:38:46,621 INFO Test, map:0.9266781356046699 rank1:3.0853658536585367
```

Has anyone been able to successfully replicate Liu Feng's metrics using his provided pretrained checkpoint? 

#### Notes
When I run covers80 inference against Liu Feng's pretrained checkpoint, I see metrics that are substantially worse. I've replicated similarly impaired metrics 3 times using variations of the inference surround (Liu Feng's original code, CoverHunterMPS, and some custom wrapper code around CoverHunterMPS which stores reference embeddings in a vector db).

Results I'm seeing look like:
```
2024-12-05 08:36:34,135 INFO map: 0.16054701169089908
2024-12-05 08:36:34,135 INFO rank1: 50.0609756097561
2024-12-05 08:36:34,136 INFO hit_rate: 0.08536585365853659
```

The results I see look much better than random, but much worse than Liu Feng's. I'm running inference on a macbook, although it seems somewhat unlikely that mps vs CUDA is the culprit...

**Comment by alanngnet** [comment]
My assumption is that his results include use of the coarse-to-fine alignment code described in their paper, and which (as I mention in my readme in this project) he had to remove as proprietary to his employer. See also #1 

In any case I have proceeded with my training without coarse-to-fine alignment and - as Liu Feng suggested might happen in his email to me last winter - I get fantastic results even without course-to-fine alignment. I'm getting .95 mAP on one of my benchmarks (Reels50easy as described at https://www.irishtune.info/public/MLdata.htm )

**Comment by alanngnet** [comment]
Thanks for the report, @brresnic. @samuel-gauthier and I also observed frustrating differences between MPS and CUDA last spring, for example MPS gets deterministic results as expected, but CUDA does not. I suspect these are probably fundamental issues at the PyTorch or MPS/CUDA level, not specific to this project? See open issue #29
